class CustomError(Error):
    pass


class CustomException(Exception):
    pass
